//! The hub's TLS identity: a user-provided certificate, or a self-signed one generated once
//! and pinned by members at enrollment.

use crate::world::crypto::sha256;
use rustls_pki_types::pem::PemObject;
use rustls_pki_types::{CertificateDer, PrivateKeyDer};
use std::path::{Path, PathBuf};
use std::sync::Arc;
use tokio_rustls::TlsAcceptor;

/// Where the hub's certificate came from.
#[derive(Clone, Debug)]
pub(crate) enum TlsSource {
    /// Generated by this hub and stored under its data directory.
    SelfSigned(PathBuf),
    /// Supplied by the operator (`--cert` / `--key`).
    Provided(PathBuf),
}

#[derive(Clone)]
pub(crate) struct ServerTls {
    pub(crate) acceptor: TlsAcceptor,
    /// SHA-256 over the leaf certificate's SubjectPublicKeyInfo, hex.
    pub(crate) spki_sha256: String,
    pub(crate) source: TlsSource,
}

impl ServerTls {
    pub(crate) fn describe(&self) -> String {
        match &self.source {
            TlsSource::SelfSigned(path) => format!(
                "self-signed certificate at {} (members pin SPKI {})",
                crate::paths::display_path(path),
                self.spki_sha256
            ),
            TlsSource::Provided(path) => format!(
                "certificate from {} (SPKI {})",
                crate::paths::display_path(path),
                self.spki_sha256
            ),
        }
    }
}

/// Loads the operator's certificate when given, otherwise the hub's own self-signed one,
/// generating it on first start.
pub(crate) fn prepare(
    data_dir: &Path,
    cert: Option<&Path>,
    key: Option<&Path>,
) -> Result<ServerTls, String> {
    let (certs, key, source) = match (cert, key) {
        (Some(cert), Some(key)) => (
            load_certs(cert)?,
            load_key(key)?,
            TlsSource::Provided(cert.to_path_buf()),
        ),
        (None, None) => {
            let directory = data_dir.join("tls");
            let cert_path = directory.join("cert.pem");
            let key_path = directory.join("key.pem");
            if !cert_path.is_file() || !key_path.is_file() {
                generate_self_signed(&directory, &cert_path, &key_path)?;
            }
            (
                load_certs(&cert_path)?,
                load_key(&key_path)?,
                TlsSource::SelfSigned(cert_path),
            )
        }
        _ => return Err("--cert and --key must be given together.".to_string()),
    };
    let leaf = certs
        .first()
        .ok_or_else(|| "The certificate file holds no certificate.".to_string())?;
    let spki_sha256 = spki_sha256(leaf)?;
    let provider = Arc::new(rustls::crypto::ring::default_provider());
    let mut config = rustls::ServerConfig::builder_with_provider(provider)
        .with_protocol_versions(&[&rustls::version::TLS13])
        .map_err(|error| format!("Cannot configure TLS 1.3: {error}"))?
        .with_no_client_auth()
        .with_single_cert(certs, key)
        .map_err(|error| {
            format!("The certificate and key do not form a usable TLS identity: {error}")
        })?;
    config.alpn_protocols = vec![b"http/1.1".to_vec()];
    Ok(ServerTls {
        acceptor: TlsAcceptor::from(Arc::new(config)),
        spki_sha256,
        source,
    })
}

/// SHA-256 of a certificate's SubjectPublicKeyInfo, the value members pin.
pub(crate) fn spki_sha256(certificate: &CertificateDer<'_>) -> Result<String, String> {
    let (_, parsed) = x509_parser::parse_x509_certificate(certificate.as_ref())
        .map_err(|error| format!("Cannot parse the TLS certificate: {error}"))?;
    Ok(hex::encode(sha256(parsed.tbs_certificate.subject_pki.raw)))
}

fn load_certs(path: &Path) -> Result<Vec<CertificateDer<'static>>, String> {
    let certs = CertificateDer::pem_file_iter(path)
        .map_err(|error| {
            format!(
                "Cannot read certificates from {}: {error}",
                crate::paths::display_path(path)
            )
        })?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|error| {
            format!(
                "Cannot parse a certificate in {}: {error}",
                crate::paths::display_path(path)
            )
        })?;
    if certs.is_empty() {
        return Err(format!(
            "{} holds no PEM certificate.",
            crate::paths::display_path(path)
        ));
    }
    Ok(certs)
}

fn load_key(path: &Path) -> Result<PrivateKeyDer<'static>, String> {
    PrivateKeyDer::from_pem_file(path).map_err(|error| {
        format!(
            "Cannot read the private key from {}: {error}",
            crate::paths::display_path(path)
        )
    })
}

fn generate_self_signed(directory: &Path, cert_path: &Path, key_path: &Path) -> Result<(), String> {
    crate::edit::private_storage::ensure_private_directory(directory, "hub TLS")?;
    let key_pair = rcgen::KeyPair::generate_for(&rcgen::PKCS_ECDSA_P256_SHA256)
        .map_err(|error| format!("Cannot generate the hub TLS key: {error}"))?;
    let mut params = rcgen::CertificateParams::new(vec!["fastctx-hub".to_string()])
        .map_err(|error| format!("Cannot describe the hub TLS certificate: {error}"))?;
    let now = time::OffsetDateTime::now_utc();
    params.not_before = now - time::Duration::days(1);
    // A century: the certificate is pinned by SPKI, never trusted by expiry, and a hub that
    // outlives it can simply be re-enrolled. Nothing here should die on a calendar date.
    params.not_after = now + time::Duration::days(365 * 100);
    params
        .distinguished_name
        .push(rcgen::DnType::CommonName, "fastctx-hub");
    let certificate = params
        .self_signed(&key_pair)
        .map_err(|error| format!("Cannot self-sign the hub TLS certificate: {error}"))?;
    crate::world::write_atomic(key_path, key_pair.serialize_pem().as_bytes())?;
    crate::world::write_atomic(cert_path, certificate.pem().as_bytes())?;
    Ok(())
}
